const actionTypes = {
    TODO_FETCH_REQUEST : "TODO_FETCH_REQUEST",
    TODO_FETCH_SUCCEEDED : "TODO_FETCH_SUCCEEDED",
    TODO_FETCH_FAILED : "TODO_FETCH_FAILED",

    LOGIN_CHECK : "LOGIN_CHECK",
    LOGIN : "LOGIN",
    IS_AUTHENTICATE : "IS_AUTHENTICATE",
    LOGIN_FAILED : "LOGIN_FAILED",
}


export default actionTypes;